create table public.manager (
    id int8 generated by default as identity,
     password varchar(255),
      username varchar(255),
       primary key (id));

create table manager_role (
    manager_id int8 not null,
     manager_role varchar(255));

create table organization (
    id int8 generated by default as identity,
    name varchar(255) not null,
      primary key (id));

create table usr (
    id int8 generated by default as identity,
     address varchar(255),
      birth_date varchar(255),
       birth_place varchar(255),
        children_count varchar(255),
         comment_1 varchar(2000),
          comment_2 varchar(2000),
           comment_3 varchar(2000),
            family_status varchar(255),
             img varchar(255),
              last_workplace varchar(255),
               phone varchar(255),
                reg_date timestamp,
                 specialty varchar(255),
                  study varchar(255),
                   update_date timestamp,
                    usr_father_name varchar(255) not null ,
                     usr_full_name varchar(255) not null ,
                        relations varchar(255),
                       organization_id int8,
                        primary key (id));

alter table if exists manager_role add constraint manager_id_role foreign key (manager_id) references public.manager;
alter table if exists usr add constraint usr_organization_id foreign key (organization_id) references organization;